// ============================================================
// routes/exam.js — Exam / MCQ Generator Route
// POST /api/exam  — Generate MCQs from a topic or text
// ============================================================

const express = require('express');
const router = express.Router();
const { protect } = require('../middleware/auth');
const ExamResult = require('../models/ExamResult');
// ── Helper: call Ollama (local fallback) ──────────────────────
const http = require('http');

function callOllama(prompt) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ model: 'llama3', prompt, stream: false });
    const options = {
      hostname: 'localhost',
      port: 11434,
      path: '/api/generate',
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }
    };
    const req = http.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(data).response || ''); }
        catch (e) { reject(new Error('Ollama response parse error')); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

const { generateExamWithPython } = require('../utils/pythonAiClient');

// ── POST /api/exam  (Protected) ───────────────────────────────
router.post('/', protect, async (req, res) => {
  try {
    const { topic, text, noteId, examType = 'mcq', numQuestions = 5, difficulty = 'medium' } = req.body;

    let promptText = '';
    let responseTopic = topic || 'Custom Text';

    if (noteId) {
      const Note = require('../models/Note');
      const note = await Note.findOne({ _id: noteId, user: req.user._id });
      if (!note) return res.status(404).json({ message: 'Note not found' });
      promptText = (note.content || '').substring(0, 15000);
      responseTopic = note.title;
    } else if (text) {
      promptText = text;
    } else if (topic) {
      promptText = topic;
    } else {
      return res.status(400).json({ message: 'Please provide a topic, text, or select a note' });
    }

    let isMcq = examType === 'mcq';

    if (isMcq) {
      try {
        // 🐍 Try Python AI Microservice first
        console.log('Sending exam generation request to Python AI Microservice...');
        const pyRes = await generateExamWithPython(responseTopic, numQuestions, difficulty, promptText);
        const questions = (pyRes.questions || []).map((q, idx) => ({
          id: idx + 1,
          question: q.question,
          options: q.options,
          correct: q.correctAnswer,
          explanation: q.explanation
        }));
        console.log('✅ Exam questions generated by Python FastAPI AI Microservice');
        return res.json({ topic: responseTopic, examType: 'mcq', questions, totalQuestions: questions.length });
      } catch (pyErr) {
        console.warn('Python AI service exam call failed, falling back to direct Gemini SDK:', pyErr.message);
      }
    }

    // Direct Gemini fallback for HTML exams or if Python failed
    const count = Math.min(parseInt(numQuestions) || 5, 10);
    const prompt = `Create exactly ${count} multiple choice questions based on: ${promptText}. Return ONLY a valid JSON array with keys id, question, options, correct, explanation.`;

    const { GoogleGenerativeAI } = require('@google/generative-ai');
    const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
    const result = await model.generateContent(prompt);
    let output = result.response.text().replace(/```json/gi, '').replace(/```/g, '').trim();

    const questions = JSON.parse(output);
    return res.json({ topic: responseTopic, examType: 'mcq', questions, totalQuestions: questions.length });

  } catch (error) {
    console.error('Exam gen error:', error);
    res.status(500).json({ message: error.message || 'Exam generation failed' });
  }
});

// ── POST /api/exam/submit (Protected) ─────────────────────────
router.post('/submit', protect, async (req, res) => {
  try {
    const { topic, score, totalQuestions } = req.body;

    if (!topic || score === undefined || !totalQuestions) {
      return res.status(400).json({ message: 'Missing required fields' });
    }

    // Backend percentage calculation
    const percentage = Math.round((Number(score) / Number(totalQuestions)) * 100);

    const result = new ExamResult({
      user: req.user._id,
      topic,
      score: Number(score),
      totalQuestions: Number(totalQuestions),
      percentage
    });

    await result.save();

    res.status(201).json({ success: true, data: result });
  } catch (error) {
    console.error('Save exam result error:', error);
    res.status(500).json({ message: 'Failed to save exam result' });
  }
});

// ── GET /api/exam/history (Protected) ─────────────────────────
// Returns past exam results for the logged-in user, newest first
router.get('/history', protect, async (req, res) => {
  try {
    const results = await ExamResult.find({ user: req.user._id })
      .sort({ createdAt: -1 })
      .limit(50); // Last 50 exams max
    res.json({ success: true, data: results });
  } catch (error) {
    console.error('Fetch exam history error:', error);
    res.status(500).json({ message: 'Failed to fetch exam history' });
  }
});

module.exports = router;
