from pydantic import BaseModel, Field
from typing import List

class KnowledgeGraphNode(BaseModel):
    id: str = Field(..., description="Unique node ID (string number)")
    label: str = Field(..., description="Concept name")
    group: str = Field(..., description="Node type: main, sub, example, algorithm")
    description: str = Field(..., description="One-sentence description of the concept")

class KnowledgeGraphEdge(BaseModel):
    from_: str = Field(..., alias="from", description="Source node ID")
    to: str = Field(..., description="Target node ID")
    label: str = Field(..., description="Relationship type label")

    class Config:
        populate_by_name = True

class KnowledgeGraphRequest(BaseModel):
    text: str = Field(..., description="Study note text to extract graph from")
    title: str = Field("Knowledge Graph", description="Title of the note / graph")

class KnowledgeGraphResponse(BaseModel):
    title: str
    nodes: List[KnowledgeGraphNode]
    edges: List[KnowledgeGraphEdge]
    node_count: int
    edge_count: int

class AskGraphRequest(BaseModel):
    question: str = Field(..., description="The user's question about the knowledge graph")
    graph_context: str = Field(..., description="The JSON string representation of the knowledge graph")

class AskGraphResponse(BaseModel):
    answer: str = Field(..., description="The AI's answer to the user's question")

class GraphInsightsRequest(BaseModel):
    graph_context: str = Field(..., description="The JSON string representation of the knowledge graph")

class GraphInsightsResponse(BaseModel):
    insights: List[str] = Field(..., description="A list of bullet-point insights generated by AI")

class ConceptExplanationRequest(BaseModel):
    concept: str = Field(..., description="The name of the concept to explain")
    graph_context: str = Field(..., description="The JSON string representation of the knowledge graph")
    note_content: str = Field(..., description="The text content of the source note")

class ConceptExplanationResponse(BaseModel):
    definition: str = Field(..., description="A formal definition of the concept")
    simple_explanation: str = Field(..., description="An easy to understand explanation of the concept")
    from_notes: str = Field(..., description="A concise summary of how the concept is used in the source note")
